# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 8fe37e6c7a4552a9585940805dc2f40436e785526ab527a8ec2815fd5ab785484be5e7065fd2ee43411f8ceab6e261508006c48528263a28fd75a83081dbcd71

test:
  secret_key_base: f59f51c2fdcedfd6dba7afd0720cb59ebbb94a0a291466c1cea1846ebf92048ec8504c3a543212d52e31ba6fdff595230619c88937fca12bf086e28af36303c2

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
